name:                Raytracing
version:             0.1.0.0
github:              "Kasama/RaytracingHaskell"
license:             MIT
author:              "Roberto Alegro"
maintainer:          "robertoaall@gmail.com"
copyright:           "2019 Roberto Alegro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Raytracing#readme>

dependencies:
- base >= 4.7 && < 5
- simple-vec3
- time
- random
- parallel

library:
  source-dirs: src

executables:
  Raytracing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Raytracing

tests:
  Raytracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Raytracing
